### PR TITLE
Feature/desktop version

### PR DESCRIPTION
**Pull request by Albinpirela**
### Add desktop version in the project
Captura de pantalla (118)
## Add skills section
Captura de pantalla (83)
## Add my works section
Captura de pantalla (116)
## Add footer and contact form
Captura de pantalla (114)

### CODE REVIEW

**Review by GerardoGomezG — CHANGES_REQUESTED** [review]
Hey pal! 👋

@AlbinPirela1 you've done a lot these last few days!
Great performance.

Please, take a look 👀 to the responsive design, specially for mobile and tablet devices 📱 (landscape and portrait viewing).

imagen

imagen

imagen

imagen

imagen

Keep working like you are! 💪

**Comment by Albinpirela** [comment]
> Hey pal! 👋
> 
> @AlbinPirela1 you've done a lot these last few days! Great performance.
> 
> Please, take a look 👀 to the responsive design, specially for mobile and tablet devices 📱 (landscape and portrait viewing).
> 
> imagen
> 
> imagen
> 
> imagen
> 
> imagen
> 
> imagen
> 
> Keep working like you are! 💪

Captura de pantalla (127)
Captura de pantalla (126)
Captura de pantalla (125)
Thanks for your suggestion here make some changes I hope they are correct 👍

**Review by GerardoGomezG — CHANGES_REQUESTED** [review]
Hello my friend!
Great improvement!
You're almost done @Albinpirela...

Please, consider changing the size of "about-me" section logo in desktop version:
imagen

Also take a look to the images sizing inside the containers (skills section), it seems they're not the same for each container (desktop-version):
imagen

In my works section, the snapshot of the website is missing. Please, check it out:
imagen

There's also something more to troubleshoot. When a link of the header is clicked to go to a section of the site, the initial part of that section results hidden below the header.

That's it bro...

**Comment by Albinpirela** [comment]
## Hi bro I have taken all your suggestions and made changes. 
Captura de pantalla (142)
# In this we see the change in size of the section logo
Captura de pantalla (141)
# and here some aesthetic details were made
Captura de pantalla (139)

### I hope you like the changes made thanks 🈂️

**Review by GerardoGomezG — APPROVED** [review]
Well done @Albinpirela ! 💪

You're done!
Congrats! 👏👏👏

Let's wait for @hendridg review tonight expecting there are no further requests

**Pull request merged**
